"""implement relationships

Revision ID: e027035e413a
Revises: 2b6c2304399d
Create Date: 2024-10-13 17:34:33.668705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e027035e413a'
down_revision = '2b6c2304399d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('activities', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('campers', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('signups', sa.Column('camper_id', sa.Integer(), nullable=False))
    op.add_column('signups', sa.Column('activity_id', sa.Integer(), nullable=False))
    op.alter_column('signups', 'time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(op.f('fk_signups_activity_id_activities'), 'signups', 'activities', ['activity_id'], ['id'])
    op.create_foreign_key(op.f('fk_signups_camper_id_campers'), 'signups', 'campers', ['camper_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_signups_camper_id_campers'), 'signups', type_='foreignkey')
    op.drop_constraint(op.f('fk_signups_activity_id_activities'), 'signups', type_='foreignkey')
    op.alter_column('signups', 'time',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('signups', 'activity_id')
    op.drop_column('signups', 'camper_id')
    op.alter_column('campers', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activities', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activities', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
